### PR TITLE
fix: improved  for in loops of unmountChildren

### PR DESCRIPTION
**Pull request by balloonzzq**
The performance of unmountChildren was improved. For in loops, the time consumption of unmountChildren was 9.42%(10.7 ms) before optimization, and 2.20%(2.2ms) after optimization.

before optimization:
image
 after optimization:
image

### CODE REVIEW

**Comment by wssgcg1213** [comment]
https://jsperf.com/forin-with-objectkeys   
it looks that forin is faster than object keys

**Comment by wssgcg1213** [comment]
benchmark 的对比数据也贴一下吧

**Comment by yuanyan** [comment]
这个即时有提升，对整体也太微乎其微了，而且代码量也变大了

**Comment by wssgcg1213** [comment]
reject

**Pull request closed without merging**
