### PR TITLE
fix: notes error

### PR DESCRIPTION
**Pull request by huangkairan**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.

### CODE REVIEW

**Review by SoloJiang — APPROVED** [review]

**Comment by SoloJiang** [comment]
@huangkairan Please sign the license

**Comment by huangkairan** [comment]
> @huangkairan Please sign the license
done

**Comment by huangkairan** [comment]
> @huangkairan Please sign the license

这个license要我打印出来然后填写完，扫描成pdf发给阿里邮箱是吗，我是阿里健康的可以不写吗

**Comment by SoloJiang** [comment]
> > @huangkairan Please sign the license
> 
> 这个license要我打印出来然后填写完，扫描成pdf发给阿里邮箱是吗，我是阿里健康的可以不写吗
不需要发送邮件

**Comment by huangkairan** [comment]
> > > @huangkairan Please sign the license
> > 
> > 
> > 这个license要我打印出来然后填写完，扫描成pdf发给阿里邮箱是吗，我是阿里健康的可以不写吗
> > 不需要发送邮件

刚才点进去验证过了，状态还是pending。。。不知道啥情况

**Comment by huangkairan** [comment]
> > > @huangkairan Please sign the license
> > 
> > 
> > 这个license要我打印出来然后填写完，扫描成pdf发给阿里邮箱是吗，我是阿里健康的可以不写吗
> > 不需要发送邮件

image

**Review by imsobear — APPROVED** [review]

**Comment by huangkairan** [comment]
我这里已经sign了
image

**Pull request merged**
