### PR TITLE
release: v1.2.3

### PR DESCRIPTION
**Pull request by SoloJiang**
- [x] fix: Encountered two children with the same key "" #2240 
- [x] fix: isValidElement should return boolean type https://github.com/alibaba/rax/pull/2265
- [x] refacor: rax-test-renderer #2268 
- [x] chore: avoid update falsy node https://github.com/alibaba/rax/pull/2275

### CODE REVIEW

**Comment by nick950222** [comment]
Question： When will 1.2.3 be officially released？

**Comment by SoloJiang** [comment]
> Question： When will 1.2.3 be officially released？

Maybe the second week in May.

**Comment by nick950222** [comment]
Question Again： When will 1.2.3 be officially released？

**Comment by SoloJiang** [comment]
+1

**Review by wssgcg1213 — APPROVED** [review]

**Review by ClarkXia — APPROVED** [review]

**Pull request merged**
