### PR TITLE
feat: multiplatform can choose if push origin config

### PR DESCRIPTION
**Pull request by frankLife**

### CODE REVIEW

**Comment by yuanyan** [comment]
unshiftOrigin naming maybe more better

**Comment by noyobo** [comment]
Really need it? Always maintain the original configuration by the user manually `shift` the original configuration.

**Comment by frankLife** [comment]
The default behavior is that origin config will be shifted as well. The aim of the change is that it will not break old use of this feature. @noyobo But I agree with your idea. 

@yuanyan Shall we change the default behavior which origin config will be shifted by user manually to keep this feature become more atomic so that user can do more detail and flexible control .

**Comment by frankLife** [comment]
After having a discussion with @noyobo ,  we decide to take a more detail name of `keepOriginConfig`. `keepOriginConfig` may be a better name ? would you have some advice ? @yuanyan

**Comment by yuanyan** [comment]
@frankLife Ok，is private or public option now？should comment in source or doc.

**Pull request closed without merging**
